#Data Properties
spring:     
  datasource:
     url: mylocalhost
     username: myusername
     password: mypass
  jpa:
    show-sql: true
    hibernate:
      ddl-auto:  update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  
  thymeleaf:
    cache: false

         
#Banner Properties
banner:
  location: classpath:/banner/banner.txt 
