#Data Properties
spring:     
  datasource:
     url: jdbc:mysql://localhost:3306/spring1?useSSL=false
     username: root
     password: Naizuore1x
  jpa:
    show-sql: true
    hibernate:
      ddl-auto:  update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  
  thymeleaf:
    cache: false
        

#Security Properties
security:
  oauth2:
    resource:
      prefer-token-info: true
      service-id: resource

#Banner Properties
banner:
  location: classpath:/banner/banner.txt 
      
    